### ISSUE TITLE
Not working in production build

### ISSUE THREAD

**Issue by Fed03** [Tonkpils/ember-sweetalert#17] opened 2019-01-30 10:42 UTC
Hi,
I used the unreleased 1.0 version of this addon throughout the whole development phase without any problem.
Sadly, building for production make this not working.

The browser spits out the error `t.default.mixin is not a function` that I tracked down to this line https://github.com/Tonkpils/ember-sweetalert/blob/adc6999004f3ee3e3650a3ec63103069f1149fad/addon/services/swal.js#L16

Thinking that it might be a conflict with another addon I created an empty emper app with only ember-sweetalert installed https://github.com/Fed03/sweetalert-test

If you run `ember s` and `ember s -prod` you'll se the error.
Let me know if I can help any further

**Comment by lindyhopchris** [comment] 2019-01-30 11:34
Hi! Yes aware of this, see #14 

If you enable the source maps as shown in that issue, does it solve your problem? Just need to check whether the issue you're encountering is a duplicate of that one or something else.

In relation to the source maps thing, I have no idea how to solve that at the moment so could do with some help if you're able to offer any.

**Comment by Fed03** [comment] 2019-01-30 13:48
I'll try and let you know. The only thing thant I think of is how we are loading sweetalert, that is through vendor shim. Maybe we could try using https://github.com/ef4/ember-auto-import

**Comment by lindyhopchris** [comment] 2019-01-30 15:15
Yeah, good idea I'll give that a go.

**Comment by Fed03** [comment] 2019-01-31 11:43
Sent PR!

**Comment by lindyhopchris** [comment] 2019-01-31 13:57
Thanks for the PR

**Closed by lindyhopchris** 2019-01-31 13:57 UTC

**Comment by Fed03** [comment] 2019-01-31 14:41
Not at all! Happy to be helpful
